#!/bin/bash
#SBATCH --account bsd
#SBATCH --partition batch
#SBATCH --nodes=1
#SBATCH --ntasks=32
##SBATCH --cpus-per-task 32
#SBATCH --mem=64g
#SBATCH --time 08:00:00
##SBATCH --output=/dev/null


module load PE-gnu/2.0
cd /home/ys0/data/HLA-clustering
for f in $(ls ./*.pdb); do
    mpirun -n 32 $ROSETTA_BIN/relax.mpi.linuxgccrelease -nstruct 20 -score:weights ref2015_cart -in:file:s $f -out:file:silent $f.out -out:file:scorefile $f.sc
done
